export const ROUTE_PATHS = {
  login: "/login",
  notFound: "/not-found",
  landing: "/landing",
  base: "/base",
  venue: "/venue",
  userManagement: "/user-management",
  nestMenu: "/nest-menu",
  link: "/nest-menu/sub-link",
  report: "/nest-menu/sub-report",
  echartsDemo: "/echarts-demo",
  custodyMenu: "/custody-menu",
  setting: "/custody-menu/setting",
  statistics: "/custody-menu/statistics",
  dailyAveragePrice: "/custody-menu/price",
  electric: "/electric",
  electricLimit: "/electric/limit",
  electricAverage: "/electric/average",
  electricBasic: "/electric/basic",

  mining: "/mining",
  miningSetting: "/mining/setting",
  miningHashRate: "/mining/hash",
};
